name: submit-android
on: workflow_dispatch

jobs:
  update:
    name: EAS Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_KEY
        run: |
          if [ -z "${{ secrets.EXPO_KEY }}" ]; then
            echo "You must provide an EXPO_KEY secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set yarn 4.1
        run: corepack enable && yarn set version berry

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Install Eas-CLI
        run: npm install -g eas-cli

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_KEY }}

      - name: Install dependencies
        working-directory: ./apps/client
        run: yarn install

      - name: Publish update
        working-directory: ./apps/client
        run: eas build --platform android --profile production --auto-submit --non-interactive
